# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "219951fa6d307722bf99e26319b550b3"
name = "AI Sales Assistant"
application_url = "https://ai-sales-frontend-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
